<?php
require_once __DIR__ . '/../../includes/config.php';
require_once __DIR__ . '/../../includes/auth_check.php';
require_once __DIR__ . '/../../includes/functions.php';
if (($_SESSION['user_role'] ?? '') !== 'super_admin') { header('Location: ' . BASE_URL . '/index.php'); exit; }
function healthRows($sql) { try { return fetchAll($sql); } catch (Throwable $e) { return []; } }
$databaseSize = healthRows("SELECT CAST(SUM(size) * 8.0 / 1024 AS DECIMAL(12,2)) AS size_mb FROM sys.database_files")[0]['size_mb'] ?? null;
$activeSessions = healthRows("SELECT COUNT(*) AS total FROM users WHERE is_active = 1 AND last_login >= DATEADD(minute, -30, GETDATE())")[0]['total'] ?? 0;
$auditToday = healthRows("SELECT COUNT(*) AS total FROM audit_log WHERE timestamp >= CAST(GETDATE() AS date)")[0]['total'] ?? 0;
$failedLogins = healthRows("SELECT TOP 25 ip_address, timestamp, JSON_VALUE(new_values, '$.username') AS attempted_username FROM audit_log WHERE action = 'Failed Login' ORDER BY timestamp DESC");
$peakHours = healthRows("SELECT TOP 5 DATEPART(hour, timestamp) AS hour_of_day, COUNT(*) AS activity_count FROM audit_log WHERE timestamp >= DATEADD(day, -30, GETDATE()) GROUP BY DATEPART(hour, timestamp) ORDER BY activity_count DESC");
$pageTitle = 'System Health'; $adminName = getFormattedUserName();
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title><?= htmlspecialchars($pageTitle) ?></title><script src="https://cdn.tailwindcss.com"></script><script>tailwind.config={darkMode:'class'};</script></head><body class="bg-gray-50 dark:bg-[#1F2937] text-gray-900 dark:text-gray-100"><div class="flex h-screen"><?php include __DIR__ . '/../../includes/sidebar.php'; ?><div class="flex-1 overflow-y-auto ml-64"><?php include __DIR__ . '/../../includes/header.php'; ?><main class="p-8 pt-28 min-h-screen space-y-6"><section class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6"><?php foreach ([['Database size', $databaseSize !== null ? $databaseSize . ' MB' : 'Unavailable'], ['Active sessions', $activeSessions], ['Audit events today', $auditToday], ['Failed logins', count($failedLogins)]] as $metric): ?><div class="bg-white dark:bg-[#111827] p-6 rounded-lg shadow-sm border border-gray-200 dark:border-slate-700"><p class="text-sm text-gray-500 dark:text-gray-400"><?= htmlspecialchars($metric[0]) ?></p><strong class="block text-3xl font-bold mt-1"><?= htmlspecialchars((string)$metric[1]) ?></strong></div><?php endforeach; ?></section><section class="bg-white dark:bg-[#111827] p-6 rounded-lg shadow-sm border border-gray-200 dark:border-slate-700"><h2 class="text-xl font-bold mb-4">Peak usage hours</h2><table class="w-full" style="table-layout:fixed"><thead class="bg-gray-100 dark:bg-slate-800"><tr><th class="px-6 py-3 text-left text-xs uppercase">Hour</th><th class="px-6 py-3 text-left text-xs uppercase">Events</th></tr></thead><tbody class="divide-y divide-gray-200 dark:divide-slate-700"><?php foreach ($peakHours as $row): ?><tr><td class="px-6 py-4 text-sm"><?= sprintf('%02d:00', (int)$row['hour_of_day']) ?></td><td class="px-6 py-4 text-sm"><?= htmlspecialchars($row['activity_count']) ?></td></tr><?php endforeach; ?></tbody></table></section><section class="bg-white dark:bg-[#111827] p-6 rounded-lg shadow-sm border border-gray-200 dark:border-slate-700"><h2 class="text-xl font-bold mb-4">Failed login attempts</h2><div class="overflow-x-auto"><table class="w-full" style="table-layout:fixed"><thead class="bg-gray-100 dark:bg-slate-800"><tr><th class="px-6 py-3 text-left text-xs uppercase">Username</th><th class="px-6 py-3 text-left text-xs uppercase">IP</th><th class="px-6 py-3 text-left text-xs uppercase">Timestamp</th></tr></thead><tbody class="divide-y divide-gray-200 dark:divide-slate-700"><?php foreach ($failedLogins as $row): ?><tr><td class="px-6 py-4 text-sm"><?= htmlspecialchars($row['attempted_username'] ?? 'Unknown') ?></td><td class="px-6 py-4 text-sm"><?= htmlspecialchars($row['ip_address'] ?? 'Unknown') ?></td><td class="px-6 py-4 text-sm"><?= htmlspecialchars($row['timestamp']) ?></td></tr><?php endforeach; ?></tbody></table></div></section></main></div></div></body></html>
